# Numpy (Cont.)

### Joining Numpy arrays

1. concatination
2. stacking
    1. stack()
    2. vertical stack
    3. horizontal stack

#### 1. Concatination

1. arrays must be of the same dimension
2. shape has to be taken care of

In [2]:
#1D
import numpy as np
a = np.arange(3)
a

array([0, 1, 2])

In [3]:
b = np.arange(5,9)
b

array([5, 6, 7, 8])

In [5]:
np.concatenate((a,b))

array([0, 1, 2, 5, 6, 7, 8])

In [6]:
np.concatenate((b,a))

array([5, 6, 7, 8, 0, 1, 2])

In [7]:
#2D

a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [9]:
b = np.array([[5,6]])
b

array([[5, 6]])

In [10]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
b = np.array([[5,6]]).reshape(2,1)
b.shape
b

array([[5],
       [6]])

In [12]:
np.concatenate((a,b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1

In [13]:
np.concatenate((a,b),axis=1) # concatenation runs along column

array([[1, 2, 5],
       [3, 4, 6]])

In [15]:
# 3D

a = np.arange(1,9).reshape(2,2,2)
print(a.shape)
print(a)

(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
b = np.array([[[9,10],[11,12]]])
print(b.shape)
print(b)

(1, 2, 2)
[[[ 9 10]
  [11 12]]]


In [18]:
np.concatenate((a,b))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [19]:
np.concatenate((a,b),axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [20]:
np.concatenate((a,b),axis=2)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

#### 2. Stacking

    1. stack()
    arrays of same dimension and same shape

In [24]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.stack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
np.stack((a,b,a))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [26]:
np.stack((a,b),axis=1)

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [28]:
#2D

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,20,30],[40,50,60]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
b

array([[10, 20, 30],
       [40, 50, 60]])

In [30]:
np.stack((a,b))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [32]:
np.stack((a,b),axis=1)

array([[[ 1,  2,  3],
        [10, 20, 30]],

       [[ 4,  5,  6],
        [40, 50, 60]]])

In [33]:
np.stack((a,b),axis=2)

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30]],

       [[ 4, 40],
        [ 5, 50],
        [ 6, 60]]])

    2. vstack() - vertical stacking
        1. In 1D number of elements is same
        2. In 2D and 3D vtsack is same as concatination along axis = 0

In [38]:
#1D

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
np.concatenate ((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
#2D

a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
#3D

a = np.arange(1,9).reshape(2,2,2)
b = np.arange(9,13).reshape(1,2,2)
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [42]:
b

array([[[ 9, 10],
        [11, 12]]])

In [43]:
np.vstack((a,b))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

    3.hsatck() - concatination along axis 1

In [44]:
#1D

a = np.array([1,2,3,4])
b = np.array([5,6,7,8,9])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
#2D

a = np.array([[1,2],[3,4]])
b = np.array([[5],[6]])
np.hstack((a,b))

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
#3D



### Splitting of Numpy arrays

1. split()
2. vsplit()
3. hsplit()

#### 1. split()

In [46]:
#1D

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.split(a,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [48]:
type(np.split(a,5))

list

In [49]:
np.split(a,6) # not possible 

ValueError: array split does not result in an equal division

In [53]:
np.split(a,[2,4,7])

[array([0, 1]), array([2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [54]:
np.split(a,[2,4,7,10,12])

[array([0, 1]),
 array([2, 3]),
 array([4, 5, 6]),
 array([7, 8, 9]),
 array([], dtype=int32),
 array([], dtype=int32)]

In [55]:
b = np.arange(11,20)
b

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [56]:
np.split(b,3)

[array([11, 12, 13]), array([14, 15, 16]), array([17, 18, 19])]

In [60]:
np.split(b,[4,6])

[array([11, 12, 13, 14]), array([15, 16]), array([17, 18, 19])]

In [61]:
#2D

a = np.arange(0,25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
np.split(a,5)

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]])]

In [66]:
np.split(a,5,axis=1)

[array([[ 0],
        [ 5],
        [10],
        [15],
        [20]]),
 array([[ 1],
        [ 6],
        [11],
        [16],
        [21]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24]])]

In [67]:
np.split(a,1,axis=1)

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])]

In [69]:
np.split(a,[2,3])

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])]

In [70]:
np.split(a,[2,3],axis=1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24]])]

In [71]:
#3D

a = np.arange(1,13).reshape(3,2,2)
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [76]:
np.split(a,3,axis=0)

[array([[[1, 2],
         [3, 4]]]),
 array([[[5, 6],
         [7, 8]]]),
 array([[[ 9, 10],
         [11, 12]]])]

In [79]:
np.split(a,2,axis=1)

[array([[[ 1,  2]],
 
        [[ 5,  6]],
 
        [[ 9, 10]]]),
 array([[[ 3,  4]],
 
        [[ 7,  8]],
 
        [[11, 12]]])]

In [85]:
np.split(a,2,axis=2)

[array([[[ 1],
         [ 3]],
 
        [[ 5],
         [ 7]],
 
        [[ 9],
         [11]]]),
 array([[[ 2],
         [ 4]],
 
        [[ 6],
         [ 8]],
 
        [[10],
         [12]]])]