## Numpy (Cont.)

### Iteration through multiple arrays

In [2]:
import numpy as np
x = np.arange(1,11).reshape(5,2)
y = np.arange(12,22).reshape(5,2)

print(x)
print(y)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]]


In [4]:
for i,j in np.nditer([x,y]):
    print(i,j)


1 12
2 13
3 14
4 15
5 16
6 17
7 18
8 19
9 20
10 21


In [5]:
for i,j in np.nditer([x,y],op_flags = ['readwrite']):
    i[...] = i+j
print(x)

[[13 15]
 [17 19]
 [21 23]
 [25 27]
 [29 31]]


### Broadcasting in numpy assays
Rules for broadcasting

1. size of each dimension is same
2. Otherwise, size of dimension should be one

 #### steps to see if arrays could be broadcasted
 
 1. chech the dimension. if the dimensions are different, make them same, we will padd ones(1) to the left of the shape of lower dimenion array
 (3,2),(1,2,3) --> (1,3,2),(1,2,3)
 2. Once dimension is same, start checking from right end of shape
 3. In each dimension , shape should be the same, or any one of them should be equal to 1

In [6]:
a = np.array([1,2,3,4])
b = np.array([5,6,7])
a+b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [7]:
a = np.array([1,2,3,4])
b = np.array([5,6,1])
a+b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [8]:
a = np.array([1,2,3,4])
b = np.array([5])
a+b

array([6, 7, 8, 9])

In [9]:
c = np.array([[1,2],[3,4],[5,6]])
d = np.array([10,12])
c+d

array([[11, 14],
       [13, 16],
       [15, 18]])

In [11]:
c = np.array([[1,2],[3,4],[5,6]])
d = np.array([10,12])
d-c

array([[ 9, 10],
       [ 7,  8],
       [ 5,  6]])

In [15]:
e = np.arange(1,7).reshape(3,2)
f = np.arange(10,50,10).reshape(2,7)
e+f

ValueError: cannot reshape array of size 4 into shape (2,7)

In [21]:
e = np.arange(1,7).reshape(3,2)
f = np.arange(10,50,10).reshape(2,2)
g = np.array([10,20])
f+g

array([[20, 40],
       [40, 60]])

In [22]:
p = np.array([[1],[2],[3]])
p

array([[1],
       [2],
       [3]])

In [24]:
q = np.array([[1,2,3]])
q

array([[1, 2, 3]])

In [26]:
for i,j in np.nditer([p,q]):
    print(i,j+1)

1 2
1 3
1 4
2 2
2 3
2 4
3 2
3 3
3 4
