# Numpy Cont.

### Array manipulations
1. insert()
2. append()
3. delete()
4. masking,filtering and searching (not a method)

#### 1. Inserting

In [2]:
import numpy as np
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [3]:
np.insert(a,2,50)

array([ 0,  1, 50,  2,  3,  4,  5,  6,  7])

In [4]:
print(a)

[0 1 2 3 4 5 6 7]


i.e its not an in placce operation original array is not affected
to change the original array

In [5]:
a = np.insert(a,2,50)
print(a)

[ 0  1 50  2  3  4  5  6  7]


In [6]:
a = np.insert(a,6,50)
a

array([ 0,  1, 50,  2,  3,  4, 50,  5,  6,  7])

In [7]:
b = np.arange(10)
b = np.insert(b,2,60)
b

array([ 0,  1, 60,  2,  3,  4,  5,  6,  7,  8,  9])

In [8]:
np.insert(b,(3,7),70) #inserting at multiple positions

array([ 0,  1, 60, 70,  2,  3,  4,  5, 70,  6,  7,  8,  9])

In [12]:
#2D
a = np.arange(8).reshape(4,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [11]:
np.insert(a,2,50) #arrays get flattened

array([ 0,  1, 50,  2,  3,  4,  5,  6,  7])

In [13]:
#inserting a row
np.insert(a,2,50,axis=0)

array([[ 0,  1],
       [ 2,  3],
       [50, 50],
       [ 4,  5],
       [ 6,  7]])

In [14]:
#inserting along column
np.insert(a,1,50,axis=1)

array([[ 0, 50,  1],
       [ 2, 50,  3],
       [ 4, 50,  5],
       [ 6, 50,  7]])

In [15]:
np.insert(a,1,[50,60],axis=0)

array([[ 0,  1],
       [50, 60],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7]])

In [16]:
np.insert(a,1,[50,60,70],axis=0) # matrix shape wont match

ValueError: could not broadcast input array from shape (1,3) into shape (1,2)

In [18]:
np.insert(a,1,[50,60,70,80],axis=1)

array([[ 0, 50,  1],
       [ 2, 60,  3],
       [ 4, 70,  5],
       [ 6, 80,  7]])

In [19]:
#3D
c = np.arange(8).reshape(2,2,2)
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [22]:
np.insert(c,2,80)

array([ 0,  1, 80,  2,  3,  4,  5,  6,  7])

In [24]:
np.insert(c,1,50,axis=0)

array([[[ 0,  1],
        [ 2,  3]],

       [[50, 50],
        [50, 50]],

       [[ 4,  5],
        [ 6,  7]]])

In [27]:
np.insert(c,2,50,axis=1)

array([[[ 0,  1],
        [ 2,  3],
        [50, 50]],

       [[ 4,  5],
        [ 6,  7],
        [50, 50]]])

In [31]:
np.insert(c,2,[10,20],axis=1)

array([[[ 0,  1],
        [ 2,  3],
        [10, 20]],

       [[ 4,  5],
        [ 6,  7],
        [10, 20]]])

In [29]:
np.insert(c,1,50,axis=2)

array([[[ 0, 50,  1],
        [ 2, 50,  3]],

       [[ 4, 50,  5],
        [ 6, 50,  7]]])

In [33]:
np.insert(c,1,[10,20],axis=2)

array([[[ 0, 10,  1],
        [ 2, 20,  3]],

       [[ 4, 10,  5],
        [ 6, 20,  7]]])

#### 2. Appending

In [34]:
b

array([ 0,  1, 60,  2,  3,  4,  5,  6,  7,  8,  9])

In [37]:
np.append(b,70)

array([ 0,  1, 60,  2,  3,  4,  5,  6,  7,  8,  9, 70])

In [40]:
np.append(b,[80,90,100])

array([  0,   1,  60,   2,   3,   4,   5,   6,   7,   8,   9,  80,  90,
       100])

In [41]:
#2D
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [43]:
np.append(a,8) #flattened

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
np.append(a,[[8,9]],axis=0) 

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [52]:
np.append(a,[[8],[9],[10],[11]],axis=1) 

array([[ 0,  1,  8],
       [ 2,  3,  9],
       [ 4,  5, 10],
       [ 6,  7, 11]])

#### 3. Deletion

In [53]:
b

array([ 0,  1, 60,  2,  3,  4,  5,  6,  7,  8,  9])

In [54]:
np.delete(b,2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
b

array([ 0,  1, 60,  2,  3,  4,  5,  6,  7,  8,  9])

In [56]:
np.delete(b,[2,5,7])

array([0, 1, 2, 3, 5, 7, 8, 9])

In [57]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [58]:
np.delete(a,2)

array([0, 1, 3, 4, 5, 6, 7])

In [69]:
np.delete(a,[2,5,7])

array([0, 1, 3, 4, 6])

In [60]:
np.delete(a,2,axis=0)

array([[0, 1],
       [2, 3],
       [6, 7]])

In [63]:
np.delete(a,(0,3),axis=0)

array([[2, 3],
       [4, 5]])

In [64]:
np.delete(a,[0,3],axis=0)

array([[2, 3],
       [4, 5]])

In [62]:
np.delete(a,1,axis=1)

array([[0],
       [2],
       [4],
       [6]])

#### masking and filtering

In [76]:
a = np.array([12,23,34,45,56])
a

array([12, 23, 34, 45, 56])

In [71]:
mask = np.array([True,False,False,False,True])
mask

array([ True, False, False, False,  True])

In [72]:
a[mask]

array([12, 56])

In [77]:
a>25

array([False, False,  True,  True,  True])

In [79]:
a[a>25]

array([34, 45, 56])

In [80]:
a%2 == 0

array([ True, False,  True, False,  True])

In [81]:
a[a%2 == 0]

array([12, 34, 56])

In [88]:
a[(a>25) & (a%2==0)]

array([34, 56])

In [89]:
(a>25) | (a%2==0)

array([ True, False,  True,  True,  True])

In [90]:
a[(a>25) | (a%2==0)]

array([12, 34, 45, 56])

In [92]:
b>2

array([False, False,  True, False,  True,  True,  True,  True,  True,
        True,  True])

In [94]:
b[b>2]

array([60,  3,  4,  5,  6,  7,  8,  9])

In [95]:
a[(a>25) | (a%2==0)]

array([12, 34, 45, 56])

In [134]:
a[(a>25) | a%2==0]

array([12])

In [135]:
a[a>25 | (a%2==0)]

array([34, 45, 56])

In [138]:
a[a%2==0]

array([12, 34, 56])

### Flipping

In [139]:
# flip()

a = np.arange(2,17,2).reshape(4,2)
a

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [145]:
np.flip(a) #both row and cokumn get flipped

array([[16, 14],
       [12, 10],
       [ 8,  6],
       [ 4,  2]])

In [142]:
np.flip(a,axis=0) # row flip

array([[14, 16],
       [10, 12],
       [ 6,  8],
       [ 2,  4]])

In [144]:
np.flip(a,axis=1) # column flip

array([[ 4,  2],
       [ 8,  6],
       [12, 10],
       [16, 14]])

In [147]:
b = np.arange(2,17,2).reshape(2,2,2)
b

array([[[ 2,  4],
        [ 6,  8]],

       [[10, 12],
        [14, 16]]])

In [148]:
np.flip(b)

array([[[16, 14],
        [12, 10]],

       [[ 8,  6],
        [ 4,  2]]])

In [150]:
np.flip(b,axis=0)

array([[[10, 12],
        [14, 16]],

       [[ 2,  4],
        [ 6,  8]]])

In [151]:
np.flip(b,axis=1)

array([[[ 6,  8],
        [ 2,  4]],

       [[14, 16],
        [10, 12]]])

In [152]:
np.flip(b,axis=2)

array([[[ 4,  2],
        [ 8,  6]],

       [[12, 10],
        [16, 14]]])

### More methods

In [158]:
# argmax and argmin
a=np.array([[1,2,7],[6,23,9]])
a

array([[ 1,  2,  7],
       [ 6, 23,  9]])

In [156]:
np.argmax(a)

4

In [157]:
np.argmin(a)

0

In [160]:
np.argmax(a,axis=0)

array([1, 1, 1], dtype=int64)

In [162]:
np.argmax(a,axis=1)

array([2, 1], dtype=int64)

In [163]:
np.argmin(a,axis=0)

array([0, 0, 0], dtype=int64)

In [164]:
np.argmin(a,axis=1)

array([0, 0], dtype=int64)

In [165]:
b = np.array([[[2,10,7],[15,89,14]],[[63,25,41],[52,100,34]]])
b

array([[[  2,  10,   7],
        [ 15,  89,  14]],

       [[ 63,  25,  41],
        [ 52, 100,  34]]])

In [166]:
np.argmax(b)

10

In [168]:
np.argmax(b,axis=0)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [169]:
np.argmax(b,axis=1)

array([[1, 1, 1],
       [0, 1, 0]], dtype=int64)

In [170]:
np.argmax(b,axis=2)

array([[1, 1],
       [0, 1]], dtype=int64)

In [171]:
# all method
a

array([[ 1,  2,  7],
       [ 6, 23,  9]])

In [173]:
np.all(a)

True

In [178]:
a=np.array([[1,2,7],[6,23,0]])
a

array([[ 1,  2,  7],
       [ 6, 23,  0]])

In [179]:
np.all(a)

False

In [181]:
a=np.array([[1,2,7],[6,23,np.NaN]]) #Not a nuber NaN
a

array([[ 1.,  2.,  7.],
       [ 6., 23., nan]])

In [182]:
np.all(a)

True

In [184]:
a=np.array([[1,2,7],[6,23,0]])
a

array([[ 1,  2,  7],
       [ 6, 23,  0]])

In [186]:
np.all(a,axis=0)

array([ True,  True, False])

In [187]:
np.all(a,axis=1)

array([ True, False])

In [188]:
# any
np.any(a)

True

In [190]:
a=np.array([[0,0],[0,0]])
a

array([[0, 0],
       [0, 0]])

In [191]:
np.any(a)

False

In [192]:
a=np.array([[1,2,0],[6,23,0]])
a

array([[ 1,  2,  0],
       [ 6, 23,  0]])

In [193]:
np.all(a,axis=0)

array([ True,  True, False])

In [195]:
a=np.array([[1,2,7],[6,23,0]])
a

array([[ 1,  2,  7],
       [ 6, 23,  0]])

In [196]:
np.all(a,axis=0)

array([ True,  True, False])