# Libraries in Data science

1. Numpy
2. Pandas
3. Matplotlib
4. Seaborn
5. Scipy

### 1. Numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

creating arrays in numpy

In [4]:
#array
a = np.array(54) # zero dimension
print(a)

54


In [6]:
a.shape # shape

()

In [7]:
a.ndim #dimension

0

In [8]:
b = np.array([1,2,3,4,5])
print(b)

print("shape: ",b.shape)
print("dimension: ",b.ndim)

[1 2 3 4 5]
shape:  (5,)
dimension:  1


In [10]:
c = np.array([[1,2,3,4],[5,6,7,8]])
print(c)

print("shape: ",c.shape)
print("dimension: ",c.ndim)

[[1 2 3 4]
 [5 6 7 8]]
shape:  (2, 4)
dimension:  2


In [12]:
d = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

print(d)

print("shape: ",d.shape)
print("dimension: ",d.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
shape:  (2, 2, 4)
dimension:  3


### special kind of arrays

1. Zeros

In [15]:
np.zeros((4,4)) # float array by default

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.zeros((4,4),dtype = int) #integer values

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
np.zeros((4,4),dtype = complex) #complex values

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

advantage of numpy array over list

In [21]:
np.zeros((4,4),dtype = int)+4 #adding with scalar values

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [23]:
np.zeros((2,3,2),dtype = int) #integer values 3 dimensional

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

2. Ones

In [24]:
np.ones(4,dtype = int)

array([1, 1, 1, 1])

In [25]:
np.ones((3,4),int)*3

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

3. arange

In [26]:
np.arange(10) # one dimensional array with values range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(4,8)

array([4, 5, 6, 7])

In [29]:
np.arange(4,8,dtype = float)

array([4., 5., 6., 7.])

In [31]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [32]:
np.arange(100,0,-2)

array([100,  98,  96,  94,  92,  90,  88,  86,  84,  82,  80,  78,  76,
        74,  72,  70,  68,  66,  64,  62,  60,  58,  56,  54,  52,  50,
        48,  46,  44,  42,  40,  38,  36,  34,  32,  30,  28,  26,  24,
        22,  20,  18,  16,  14,  12,  10,   8,   6,   4,   2])

reshape

In [33]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [35]:
np.arange(10).reshape(1,2,5)

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [37]:
np.arange(10).reshape(2,1,5)

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [38]:
np.arange(10).reshape(2,5,1)

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

4. linspace

In [41]:
np.linspace(0,9,10) # 0 to 9 with 10 elements

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
np.linspace(0,1,9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [45]:
np.linspace(0.25,0.75,12,endpoint=False) # endpoint (.75) is not included

array([0.25      , 0.29166667, 0.33333333, 0.375     , 0.41666667,
       0.45833333, 0.5       , 0.54166667, 0.58333333, 0.625     ,
       0.66666667, 0.70833333])

In [46]:
np.linspace(0.25,0.75,12,endpoint=True) # endpoint (.75) included

array([0.25      , 0.29545455, 0.34090909, 0.38636364, 0.43181818,
       0.47727273, 0.52272727, 0.56818182, 0.61363636, 0.65909091,
       0.70454545, 0.75      ])

5. eye (identity matrix)

In [47]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
np.eye(3)*6

array([[6., 0., 0.],
       [0., 6., 0.],
       [0., 0., 6.]])

In [50]:
np.eye(3,2) # non square matrix

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [51]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [52]:
np.eye(3,k=1) #diagonal starts from 1st column

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [53]:
np.eye(3,k=-1) #diagonal starts from 1st row

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [56]:
np.eye(4,3,k=-1,dtype=int) #diagonal starts from 1st row

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

6. random.randint

In [58]:
np.random.randint(10) # create an array of range(10)

0

In [59]:
np.random.randint(10) # create an array of range(10)

3

In [60]:
np.random.randint(10,100) # create an array of range(10,100)

99

In [61]:
np.random.randint(10,100) # create an array of range(10,100)

29

In [63]:
np.random.randint(10,100,(3,3)) # create an array of 3x3 matrix with values of range(10,100)

array([[67, 25, 53],
       [58, 55, 62],
       [98, 53, 92]])

In [64]:
np.random.randint(10,100,(3,3)) # create an array of 3x3 matrix with values of range(10,100)

array([[65, 97, 15],
       [41, 60, 45],
       [34, 92, 64]])

In [66]:
np.random.randint(10,100,(3,3,2)) # create a 3D array of 3x2 matrix with values of range(10,100)

array([[[10, 41],
        [46, 81],
        [60, 42]],

       [[82, 11],
        [43, 34],
        [33, 71]],

       [[59, 18],
        [29, 82],
        [42, 88]]])

7. identity

In [69]:
np.identity(4,dtype = int) #square matrix (identity)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [70]:
np.identity(4,dtype = int)*5

array([[5, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 5]])

In [75]:
np.identity(4,dtype = complex) * 5

array([[5.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 5.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 5.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 5.+0.j]])

In [76]:
dir(np) # dorectory of numpy

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__pac

to get diagonal elements

In [77]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
np.diag(a) # diagonal of matrix

array([1, 5, 9])

In [80]:
np.diag(a,k=1)

array([2, 6])

In [81]:
np.diag(a,k=-1)

array([4, 8])

In [89]:
np.diag(np.fliplr(a))

array([3, 5, 7])

In [90]:
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [93]:
np.tril(a,k=1)

array([[1, 2, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
np.triu(a)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [92]:
np.triu(a,k=1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

### INDEX
indexing of n dimensional arrays

In [94]:
a = np.array ([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [95]:
a[0]

1

In [96]:
a[3]

4

In [98]:
a[-2]

5

for 2D array

In [100]:
b = np.arange(1,7).reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
b[0,2]

3

In [102]:
b[0][2]

3

3D array

In [103]:
c = np.arange(1,13).reshape(2,2,3)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [104]:
c[0,1,1]

5

In [105]:
c[1,0,2]

9

### SLICING

In [107]:
a

array([1, 2, 3, 4, 5, 6])

In [109]:
a[2:6]

array([3, 4, 5, 6])

In [110]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
b[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [112]:
d = np.array([[12,34,56],[45,32,90],[89,42,65],[23,91,100]])
d

array([[ 12,  34,  56],
       [ 45,  32,  90],
       [ 89,  42,  65],
       [ 23,  91, 100]])

In [113]:
d[1:3,1:3]

array([[32, 90],
       [42, 65]])

In [115]:
d[0:4:2,0:4:2] # skipping one element

array([[12, 56],
       [89, 65]])