# Scipy (Scientific Python)
some major libraries avalibale in it are
1. integration : scipy.integrate
2. optimazation : scipy.optimize
3. fourier transform : scipy.fft
4. signal processing : scipy.signal
5. Linear algebra : scipy.linalg
6. statistics : scipy.stats
7. image processing : scipy.ndimage
8. File I/O : scipy.io
9. constants : scipy.const

etc

## 1. Constants 
submdoule act as a library for scientific constants

importing library

In [1]:
from scipy import constants as cts

getting available constants

In [2]:
print(dir(cts))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_codata', '_constants', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'grain', '

In [3]:
dir(cts)

['Avogadro',
 'Boltzmann',
 'Btu',
 'Btu_IT',
 'Btu_th',
 'ConstantWarning',
 'G',
 'Julian_year',
 'N_A',
 'Planck',
 'R',
 'Rydberg',
 'Stefan_Boltzmann',
 'Wien',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_codata',
 '_constants',
 '_obsolete_constants',
 'acre',
 'alpha',
 'angstrom',
 'arcmin',
 'arcminute',
 'arcsec',
 'arcsecond',
 'astronomical_unit',
 'atm',
 'atmosphere',
 'atomic_mass',
 'atto',
 'au',
 'bar',
 'barrel',
 'bbl',
 'blob',
 'c',
 'calorie',
 'calorie_IT',
 'calorie_th',
 'carat',
 'centi',
 'codata',
 'constants',
 'convert_temperature',
 'day',
 'deci',
 'degree',
 'degree_Fahrenheit',
 'deka',
 'dyn',
 'dyne',
 'e',
 'eV',
 'electron_mass',
 'electron_volt',
 'elementary_charge',
 'epsilon_0',
 'erg',
 'exa',
 'exbi',
 'femto',
 'fermi',
 'find',
 'fine_structure',
 'fluid_ounce',
 'fluid_ounce_US',
 'fluid_ounce_imp',
 'foot',
 'g',
 'gallon',
 'gallon_US',
 'g

printing some constants

In [4]:
cts.pi

3.141592653589793

In [5]:
print('speed of light in vaccum: ', cts.c)

speed of light in vaccum:  299792458.0


In [6]:
print('gravitational constants: ',cts.G)

gravitational constants:  6.6743e-11


searching for constatns

In [7]:
cts.find('mass')

['Planck mass',
 'Planck mass energy equivalent in GeV',
 'W to Z mass ratio',
 'alpha particle mass',
 'alpha particle mass energy equivalent',
 'alpha particle mass energy equivalent in MeV',
 'alpha particle mass in u',
 'alpha particle molar mass',
 'alpha particle relative atomic mass',
 'alpha particle-electron mass ratio',
 'alpha particle-proton mass ratio',
 'atomic mass constant',
 'atomic mass constant energy equivalent',
 'atomic mass constant energy equivalent in MeV',
 'atomic mass unit-electron volt relationship',
 'atomic mass unit-hartree relationship',
 'atomic mass unit-hertz relationship',
 'atomic mass unit-inverse meter relationship',
 'atomic mass unit-joule relationship',
 'atomic mass unit-kelvin relationship',
 'atomic mass unit-kilogram relationship',
 'atomic unit of mass',
 'deuteron mass',
 'deuteron mass energy equivalent',
 'deuteron mass energy equivalent in MeV',
 'deuteron mass in u',
 'deuteron molar mass',
 'deuteron relative atomic mass',
 'deutero

In [8]:
cts.neutron_mass

1.67492749804e-27

In [11]:
cts.physical_constants['neutron mass'] #(value,unit,uncertainity )

(1.67492749804e-27, 'kg', 9.5e-37)

In [12]:
cts.find('light')

['speed of light in vacuum']

In [13]:
cts.physical_constants['speed of light in vacuum']

(299792458.0, 'm s^-1', 0.0)

In [15]:
print(f"speed of light in vacuum is {cts.physical_constants['speed of light in vacuum'][0]} in unit of {cts.physical_constants['speed of light in vacuum'][1]} with an uncertainty of {cts.physical_constants['speed of light in vacuum'][2]}")

speed of light in vacuum is 299792458.0 in unit of m s^-1 with an uncertainty of 0.0


In [19]:
cts.find('Golden ratio')

[]

In [20]:
cts.golden

1.618033988749895

In [22]:
cts.physical_constants['golden ratio']

KeyError: 'golden ratio'

In [25]:
cts.Mathematical_constants

AttributeError: module 'scipy.constants' has no attribute 'Mathematical_constants'

## 2. Linear Algebra
deals with **linear equations (degree one)**
<p> $y=mx+c$<br>
$y=ax+by+c$ </p>

consider the equation to solve
<p>$x+3y+5z=10$<br>
$2x+5y+z=8$<br>
$2x+3y+8z=3$</p>

In [32]:
import numpy as np
from scipy import linalg

In [28]:
a = np.array([[1,3,5],[2,5,1],[2,3,8]])
a

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [31]:
b = np.array([[10],[8],[3]])
b

array([[10],
       [ 8],
       [ 3]])

In [33]:
solution  = linalg.solve(a,b)
solution

array([[-9.28],
       [ 5.16],
       [ 0.76]])

another example
<p>$2x+3y=11$<br>
$3x+2y=9$</p>

In [35]:
a = np.array([[2,3],[3,2]])
a

array([[2, 3],
       [3, 2]])

In [36]:
b = np.array([[11],[9]])
b

array([[11],
       [ 9]])

In [40]:
solution = linalg.solve(a,b)
solution

array([[1.],
       [3.]])

Note the ***order*** of a and b

In [41]:
solution = linalg.solve(b,a)
solution

ValueError: Input a needs to be a square matrix.

### Matrices
inverse of matrix
$\left[\begin{array}{ccc}
8 & 7\\
2 & 3
\end{array}\right]$

In [42]:
a = np.array([[8,7],[2,3]])
a

array([[8, 7],
       [2, 3]])

In [43]:
linalg.inv(a)

array([[ 0.3, -0.7],
       [-0.2,  0.8]])

In [44]:
linalg.det(a)

10.0

**another example**<br>
consider the matrix
$\left[\begin{array}{ccc}
3 & 1&-1\\
2 & -2&0\\
1 & 2&-1
\end{array}\right]$

In [48]:
a = np.array([[3,1,-1],[2,-2,0],[1,2,-1]])
a

array([[ 3,  1, -1],
       [ 2, -2,  0],
       [ 1,  2, -1]])

In [49]:
linalg.det(a)

2.0

In [50]:
linalg.inv(a)

array([[ 1. , -0.5, -1. ],
       [ 1. , -1. , -1. ],
       [ 3. , -2.5, -4. ]])

In [ ]:
x