## Numpy (Cont.)

slicing 3D array

In [1]:
import numpy as np

c = np.arange(1,19).reshape(3,2,3)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [6]:
c[0:2,:,1:]

array([[[ 2,  3],
        [ 5,  6]],

       [[ 8,  9],
        [11, 12]]])

In [11]:
c[1:,:1,:]

array([[[ 7,  8,  9]],

       [[13, 14, 15]]])

In [13]:
c[1:,0,:] # why?

array([[ 7,  8,  9],
       [13, 14, 15]])

### Attributes

1. size

In [14]:
a = np.arange(0,9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
a.size #number of elements in an array

9

In [16]:
a = np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
a.size

9

2. shape

In [19]:
a.shape # gives (rows,column) 

(3, 3)

3. dimension

In [21]:
a.ndim

2

4. dtype

In [24]:
a.dtype # gives datatype

dtype('int32')

In [27]:
fruits = np.array(["apple","orange","kiwi"])
print(fruits.dtype)

fruits2 = np.array(["apple","oranges","kiwi"])
print(fruits2.dtype)

<U6
<U7


In [28]:
bool_array = np.array([True,False,True,True,False])
bool_array.dtype

dtype('bool')

In [29]:
complex_array = np.array([12+3j,5+6j])
complex_array.dtype

dtype('complex128')

In [34]:
float_array = np.array([12.5,3.0,7])
print(float_array.dtype)
print(float_array)

float64
[12.5  3.   7. ]


5. nbytes

In [36]:
a = np.arange(0,9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
a.nbytes # total bytes of that array

36

In [53]:
b = np.arange(2.2) ## ?
print(b)
print(b.nbytes)

[0. 1. 2.]
24


### Array Methods

1. reshape

In [55]:
a = np.arange(1,11)
print(a)
print(a.size)

[ 1  2  3  4  5  6  7  8  9 10]
10


In [56]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [57]:
a.reshape(5,2,1)

array([[[ 1],
        [ 2]],

       [[ 3],
        [ 4]],

       [[ 5],
        [ 6]],

       [[ 7],
        [ 8]],

       [[ 9],
        [10]]])

In [60]:
a.reshape(2,1,5)

array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]]])

2. flatten and ravel

In [61]:
b = a.reshape(5,2,1)
b

array([[[ 1],
        [ 2]],

       [[ 3],
        [ 4]],

       [[ 5],
        [ 6]],

       [[ 7],
        [ 8]],

       [[ 9],
        [10]]])

In [65]:
flatten = b.flatten()
flatten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
ravel = b.ravel()
ravel

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
flatten[2]=36 # does not change the original array(b)
print(flatten)

[ 1  2 36  4  5  6  7  8  9 10]


In [68]:
b

array([[[ 1],
        [ 2]],

       [[ 3],
        [ 4]],

       [[ 5],
        [ 6]],

       [[ 7],
        [ 8]],

       [[ 9],
        [10]]])

In [70]:
ravel[2]=36 # change the original array(b)

In [71]:
b

array([[[ 1],
        [ 2]],

       [[36],
        [ 4]],

       [[ 5],
        [ 6]],

       [[ 7],
        [ 8]],

       [[ 9],
        [10]]])

In [72]:
a

array([ 1,  2, 36,  4,  5,  6,  7,  8,  9, 10])

In [73]:
a_slice = a[5:9]
a_slice

array([6, 7, 8, 9])

In [74]:
a_slice[1] = 14
a_slice

array([ 6, 14,  8,  9])

In [75]:
a

array([ 1,  2, 36,  4,  5,  6, 14,  8,  9, 10])

In [76]:
a_alice = np.copy(a[2:6]) # to work on a copy
a_slice

array([ 6, 14,  8,  9])

In [77]:
a_slice[1]=100
a_slice

array([  6, 100,   8,   9])

In [78]:
a

array([  1,   2,  36,   4,   5,   6, 100,   8,   9,  10])

In [80]:
a_view = a.view()
a_view[3]=16
print(a_view)
print(a)

[  1   2  36  16   5   6 100   8   9  10]
[  1   2  36  16   5   6 100   8   9  10]


## Iteration through numpy arrays
1. for loop
2. nd iter

for loop

In [81]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
for i in range(a.size):
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 

In [84]:
a2 = np.arange(10).reshape(2,5)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [85]:
for i in a2:
    for j in i:
        print(j,end=" ")

0 1 2 3 4 5 6 7 8 9 

In [87]:
a3 = np.arange(10).reshape(2,5,1)
a3

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

In [89]:
for i in a3:
    for j in i:
        for k in j:
            print(k,end=" ")

0 1 2 3 4 5 6 7 8 9 

In [90]:
for i in a:
    print(i*2,end=" ")

0 2 4 6 8 10 12 14 16 18 

In [91]:
for i in a:
    i = i*2
    
print(a)

[0 1 2 3 4 5 6 7 8 9]


nditer() for array iteration

In [93]:
a*2  ## ?

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [94]:
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [95]:
for i in np.nditer(a2,order = "C"):
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 

In [97]:
for i in np.nditer(a2,order = "F"):
    print(i,end=" ")

0 5 1 6 2 7 3 8 4 9 

In [99]:
for i in np.nditer(a2):
    i=i*2
print(a2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [108]:
for i in np.nditer(a2,op_flags = ['readwrite']):
    i[...]=i*2
print(a2)

[[ 0  0  4  4  8]
 [ 8 12 12 16 16]]


In [109]:
for i in np.nditer(a2,flags=['external_loop']):
    print(i)

[ 0  0  4  4  8  8 12 12 16 16]


In [110]:
for i in np.nditer(a2,flags=['external_loop'],order="F"):
    print(i)

[0 8]
[ 0 12]
[ 4 12]
[ 4 16]
[ 8 16]
