# Scipy Cont.
## Linear Algebra functions in SciPy
solving linear equaions

$7x + 2y = 8$<br>
$4x + 5y = 10$

In [1]:
import numpy as np
from scipy import linalg

In [2]:
a = np.array([[7,2],[4,5]]) # 
b = np.array([8,10]) # constants

In [4]:
print(linalg.solve(a,b)) # solving for x,y

[0.74074074 1.40740741]


inverse of a matrix 

In [5]:
a

array([[7, 2],
       [4, 5]])

In [6]:
b

array([ 8, 10])

In [7]:
linalg.inv(a)

array([[ 0.18518519, -0.07407407],
       [-0.14814815,  0.25925926]])

determinant 

In [8]:
linalg.det(a)

27.0

#### eigen values and eigen vectors

In [12]:
# let M be a 2D matrix
M = np.array([[9,3],[2,4]])
val = linalg.eigvals(M) # eigen values
val

array([10.+0.j,  3.+0.j])

In [14]:
val, vec = linalg.eig(M) # eigen values and eigen vectors
print(val,vec, sep='\n\n')

[10.+0.j  3.+0.j]

[[ 0.9486833  -0.4472136 ]
 [ 0.31622777  0.89442719]]


#### singular value decomposition

In [25]:
B = np.array([[-4,-7,8],[1,4,4]])
linalg.svd(B)

(array([[-1.00000000e+00, -9.77496868e-18],
        [-9.77496868e-18,  1.00000000e+00]]),
 array([11.35781669,  5.74456265]),
 array([[ 0.35218036,  0.61631563, -0.70436073],
        [ 0.17407766,  0.69631062,  0.69631062],
        [ 0.91960098, -0.36784039,  0.13794015]]))

In [62]:
A = np.array([[-4,-7],[1,4]])
A

array([[-4, -7],
       [ 1,  4]])

In [63]:
A.transpose()

array([[-4,  1],
       [-7,  4]])

In [64]:
linalg.svd(A) # return U, D, Vt

(array([[-0.89442719,  0.4472136 ],
        [ 0.4472136 ,  0.89442719]]),
 array([9., 1.]),
 array([[ 0.4472136 ,  0.89442719],
        [-0.89442719,  0.4472136 ]]))

In [65]:
np.linalg.svd(A)

(array([[-0.89442719,  0.4472136 ],
        [ 0.4472136 ,  0.89442719]]),
 array([9., 1.]),
 array([[ 0.4472136 ,  0.89442719],
        [-0.89442719,  0.4472136 ]]))

lets find it manually 

In [68]:
AAT = np.dot(A,A.transpose()) #U
AAT

array([[ 65, -32],
       [-32,  17]])

In [73]:
x,y = linalg.eig(AAT)
y

array([[ 0.89442719,  0.4472136 ],
       [-0.4472136 ,  0.89442719]])

In [79]:
ATA = A.transpose()@A
ATA

array([[17, 32],
       [32, 65]])

In [80]:
linalg.eigvals(ATA) # D will be square root of this

array([ 1.+0.j, 81.+0.j])

In [81]:
x,y = linalg.eig(ATA)
y

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

In [82]:
y.transpose() #VT

array([[-0.89442719,  0.4472136 ],
       [-0.4472136 , -0.89442719]])

In [83]:
C = np.array([[4,0],[3,-5]])
C

array([[ 4,  0],
       [ 3, -5]])

In [84]:
#U
ATA = np.dot()

TypeError: dot() missing 2 required positional arguments: 'a' and 'b'

rank of matrix (number of non zero eigen values)

In [44]:
A

array([[-4, -7],
       [ 1,  4]])

In [49]:
from numpy.linalg import matrix_rank
matrix_rank(A)

2

norm of a matrix

In [85]:
A = np.array([[2, 2],
              [1, 1]])
u, s, vh = np.linalg.svd(A, full_matrices=False)

smat = np.diag(s)

def is_unary(A):
    return np.allclose(A @ A.T, np.eye(A.shape[0]))

print(f"Is u unary? {is_unary(u)}")
print(f"Is vh unary? {is_unary(vh)}")
print(f"original matrix A")
print(A)
print("Reconstructed matrix A")
print(u @ smat @ vh)

def check_svd(A, u, s, vh):
    smat = np.diag(s)
    c1 = is_unary(u)
    c2 = is_unary(vh)
    c3 = np.allclose(A, u @ smat @ vh)
    success = c1 and c2 and c3
    if not success:
        raise Exception("numpy SVD failed")

for i in range(100):
    A = np.random.rand(100, 100)
    u, s, vh = np.linalg.svd(A, full_matrices=False)
    check_svd(A, u, s, vh)

print("All tests passed")

Is u unary? True
Is vh unary? True
original matrix A
[[2 2]
 [1 1]]
Reconstructed matrix A
[[2. 2.]
 [1. 1.]]
All tests passed
